// Import tests
// import attack from './GameOperations/scenario-attack';
import userMove from './move';
import fleetLockin from './fleetLockin';
import gameStorageUnit from './gameStorageUnit';
// import upgradeTests from './core/upgrade-tests';
// import depositPoolTests from './deposit/deposit-pool-tests';
// import minipoolTests from './minipool/minipool-tests';
// import minipoolStatusTests from './minipool/minipool-status-tests';
// import networkBalancesTests from './network/network-balances-tests';
// import networkFeesTests from './network/network-fees-tests';
// import networkWithdrawalTests from './network/network-withdrawal-tests';
// import nodeDepositTests from './node/node-deposit-tests';
// import nodeManagerTests from './node/node-manager-tests';
// import depositSettingsTests from './settings/deposit-settings-tests';
// import minipoolSettingsTests from './settings/minipool-settings-tests';
// import networkSettingsTests from './settings/network-settings-tests';
// import nodeSettingsTests from './settings/node-settings-tests';
// import nethTests from './token/neth-tests';
// import rethTests from './token/reth-tests';
gameStorageUnit();
userMove();
fleetLockin();
// upgradeTests();
// depositPoolTests();
// minipoolTests();
// minipoolStatusTests();
// networkBalancesTests();
// networkFeesTests();
// networkWithdrawalTests();
// nodeDepositTests();
// nodeManagerTests();
// depositSettingsTests();
// minipoolSettingsTests();
// networkSettingsTests();
// nodeSettingsTests();
// nethTests();
// rethTests();
